version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=password
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - my-db:/var/run/postgres
volumes:
  my-db: